version: '3.3'

networks:
  sharescreen:

services:
  server:
    image: 'node:14'
    container_name: server_sharescreen
    restart: unless-stopped
    ports:
      - '5000:5000'
    command: >
      bash -c "npm install -g npm@latest
      && cd /server
      && npm i
      && npm run build
      && npm start"
    volumes:
      - './server:/server'
    networks:
      - sharescreen

  # mongo:
  #   image: 'mongo:latest'
  #   container_name: mongo
  #   restart: unless-stopped
  #   user: root
  #   ports:
  #     - '27017:27017'
  #   environment:
  #     TZ: Europe/Rome
  #   volumes:
  #     - './mongodata:/data/db'
  #   networks:
  #     - sharescreen
  
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq_sharescreen
    restart: unless-stopped
    user: root
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: roomrabbit
      RABBITMQ_DEFAULT_PASS: fr4g0l0n3
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - './rabbitdata:/var/lib/rabbitmq'
    networks:
      - sharescreen